### ISSUE TITLE
Application Crashing

### ISSUE THREAD

**Issue by josephwegner** [larvalabs/pullup#327]
Viewing the logs from local, it looks like most pages are timing out..  However, I did just see this error pop up:

```
/app/controllers/news.js:483
4/1/2014 8:59:12 AMweb.1 newsItems.forEach(function (item) {
4/1/2014 8:59:12 AMweb.1 ^
4/1/2014 8:59:12 AMweb.1TypeError: Object # has no method 'forEach'
4/1/2014 8:59:12 AMweb.1 at sortByScore (/app/controllers/news.js:483:13)
4/1/2014 8:59:12 AMweb.1 at /app/controllers/news.js:384:19
4/1/2014 8:59:12 AMweb.1 at Promise. (/app/controllers/votes.js:146:5)
4/1/2014 8:59:12 AMweb.1 at Promise. (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
4/1/2014 8:59:12 AMweb.1 at Promise.EventEmitter.emit (events.js:95:17)
4/1/2014 8:59:12 AMweb.1 at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
4/1/2014 8:59:12 AMweb.1 at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
4/1/2014 8:59:12 AMweb.1 at Promise.resolve (/app/node_modules/mongoose/lib/promise.js:108:15)
4/1/2014 8:59:12 AMweb.1 at Promise. (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
4/1/2014 8:59:12 AMweb.1 at Promise.EventEmitter.emit (events.js:95:17)
4/1/2014 8:59:12 AMweb.1app.js has exited after 3 restarts
4/1/2014 8:59:12 AMweb.1/app/controllers/news.js:483
4/1/2014 8:59:12 AMweb.1 newsItems.forEach(function (item) {
```

**Comment by rickhanlonii** [comment]
I don't think this is an issue any more, feel free to re-open if I'm wrong.
